resolver: lts-15.13

packages:
- megaexample
- opentelemetry
- opentelemetry-extra
- opentelemetry-lightstep
- opentelemetry-proto
- opentelemetry-wai

extra-deps:
- ghc-events-0.13.0
- ghc-trace-events-0.1.0.1
