name: Build
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  linux-cabal:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['8.6', '8.8', '8.10']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      name: Cache ~/.cabal/packages
      with:
        path: ~/.cabal/packages
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-packages
    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store
    - uses: actions/cache@v1
      name: Cache dist-newstyle
      with:
        path: dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-dist-newstyle
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.0'
    - name: Update cabal package database
      run: cabal update
    - name: Build
      run: |
        cabal build all
    - name: Test
      run: |
        cd opentelemetry
        cabal install tasty-discover
        env PATH="$HOME/.cabal/bin:$PATH" cabal test

  linux-stack:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack-yaml: ['stack.yaml', 'stack-8.6.yaml', 'stack-8.10.1.yaml']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.stack-yaml }}-stack-home
    - uses: actions/cache@v1
      name: Cache .stack-work
      with:
        path: .stack-work
        key: ${{ runner.os }}-${{ matrix.stack-yaml }}-stack-work
    - name: Install stack
      run: which stack || curl -sSL https://get.haskellstack.org/ | sh
    - name: Install GHC
      run: |
        stack setup --stack-yaml ${{ matrix.stack-yaml }}
    - name: Build
      run: |
        stack build --no-interleaved-output --fast --stack-yaml ${{ matrix.stack-yaml }}
    - name: Test
      run: |
        stack test --fast --stack-yaml ${{ matrix.stack-yaml }}
    - name: Bench
      run: |
        stack bench --stack-yaml ${{ matrix.stack-yaml }} opentelemetry-extra --benchmark-arguments '+RTS -l'

  macos-stack:
    runs-on: macOS-latest
    strategy:
      matrix:
        stack-yaml: ['stack.yaml', 'stack-8.10.1.yaml']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.stack-yaml }}-stack-home
    - uses: actions/cache@v1
      name: Cache .stack-work
      with:
        path: .stack-work
        key: ${{ runner.os }}-${{ matrix.stack-yaml }}-stack-work
    - name: Install stack
      run: which stack || curl -sSL https://get.haskellstack.org/ | sh
    - name: Install GHC
      run: |
        stack setup --stack-yaml ${{ matrix.stack-yaml }}
    - name: Build
      run: |
        stack build --no-interleaved-output  --fast --stack-yaml ${{ matrix.stack-yaml }}
    - name: Test
      run: |
        stack test --fast --stack-yaml ${{ matrix.stack-yaml }}
    - name: Bench
      run: |
        stack bench --stack-yaml ${{ matrix.stack-yaml }} opentelemetry-extra --benchmark-arguments '+RTS -l'

  win-cabal:
    runs-on: windows-latest
    strategy:
      matrix:
        ghc: ['8.10']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      name: Cache ~/.cabal/packages
      with:
        path: ~/.cabal/packages
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-packages
    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store
    - uses: actions/cache@v1
      name: Cache dist-newstyle
      with:
        path: dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-dist-newstyle
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.0'
    - name: Update cabal package database
      run: cabal update
    - name: Build
      run: |
        cabal build all -v
